name: Generate Snake Animation

on:
  schedule: # Runs at 6:00 every day
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the snake animation using the latest version of the action
      - name: Generate Snake
        uses: Platane/snk@main
        with:
          github_user_name: "skillerious"  # Your GitHub username
          outputs: dist/github-snake.svg

      # Commit the new SVG file to the repository
      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/github-snake.svg
          git commit -m "Generated snake animation"
          git push
